version: '3'

services:
  redis:
    image: redis:7.0.8-alpine
    container_name: redis-server
    ports:
      - 6379:6379
    networks:
      - orderly-net

  postgres:
    image: postgres:latest
    container_name: postgres-database
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
    env_file:
      - .env.production
    volumes:
      - postgres:/data/postgres
    networks:
      - orderly-net
    restart: unless-stopped

  api:
    build: .
    container_name: node-api
    ports:
      - 3000:3000
    networks:
      - orderly-net
    depends_on:
      - redis
      - postgres
    restart: always
    links:
      - postgres
      - redis
    env_file:
      - .env.production

networks:
  orderly-net:
    driver: bridge

volumes:
  postgres:
