apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api-container
        image: tribofustack/orderly:1
        workingDir: /usr/api
        resources:
          limits:
            memory: "500Mi"
            cpu: 1
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: api-configmap
        livenessProbe:
          httpGet:
            path: /orders
            port: 3000
          periodSeconds: 10
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /orders
            port: 3000
          periodSeconds: 10
          initialDelaySeconds: 10
        startupProbe:
          httpGet:
            path: /orders
            port: 3000
          periodSeconds: 30
          initialDelaySeconds: 60