apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-statefulset
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  serviceName: db-service
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db-container
        image: postgres:latest
        ports:
        - containerPort: 5432
        envFrom:
          - configMapRef:
              name: db-configmap
        volumeMounts:
          - name: postgres
            mountPath: /data/postgres
        livenessProbe:        
          tcpSocket:
            port: 5432
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 20
        readinessProbe:
          tcpSocket:
              port: 5432
          periodSeconds: 10
          failureThreshold: 5
          initialDelaySeconds: 3
        startupProbe:
          tcpSocket:
              port: 5432
          periodSeconds: 30
          failureThreshold: 5
          initialDelaySeconds: 60
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: database-pv
        
        